
// This file was auto-generated by ML.NET Model Builder. 

using ReconocimientoModel_ConsoleApp1;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\Raul\Downloads\kaggle_cats_dogs_small\kaggle_cats_dogs_small\train\cats\cat.0.jpg");
ReconocimientoModel.ModelInput sampleData = new ReconocimientoModel.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var sortedScoresWithLabel = ReconocimientoModel.PredictAllLabels(sampleData);
Console.WriteLine($"{"Class",-40}{"Score",-20}");
Console.WriteLine($"{"-----",-40}{"-----",-20}");

foreach (var score in sortedScoresWithLabel)
{
    Console.WriteLine($"{score.Key,-40}{score.Value,-20}");
}
